language: python
python:
  - "2.7"
before_install:
  openssl aes-256-cbc -K $encrypted_eab4b1048f57_key -iv $encrypted_eab4b1048f57_iv -in keys.py.enc -out configuration/keys.py -d
install:
  - pip install -r requirements/common.txt
  - pip install -r requirements/prod.txt 
  - pip install coveralls
script:
  - coverage run --omit='/home/travis/virtualenv/*' manage.py test tickets.test_models
after_success:
  coveralls
