language: python
python:
- '2.7'
env:
  matrix:
  global:
  - secure: ryoVfJAxug+rmTxt0++MXHQe0T21AqJXdaJ3GiyvVMhfszSFQmA4/TTmHNK8cPdN0tKCg/fqERW9lJvS4iX+Xrs7g8DwsYJHst3cZ0lnjN06WmO6rbXx3MDzboKjccCTqAacsgdrhnrEkCeuMe2pfZ7lTK/u9CIjnSz7ujaxoc9cCSUsgQNdnGmf5eq7YYXpLFvbAprejdox2CE1/tsjmeAL6UBqKWJA9bnlLzK9WygVxDC5lxWRw6TgsBdTfSjHP5e8/o2zmFcK2aC5FNy3zZhwdgmTX7avKCEe5ZjFB/9Zaa0Bgo9ybVuNL7UpCjwK1BtFf7Kkflr/+HhK1fgeN/sOR5Qgaum/68YbwVISwmpt8vrYTqbbPeTnQudrb/UKFFsLtBdpUOVH5k+18pn5J37KgFOAE9J9Xv3YcKvofU826R7c2LUf45TSdwgr4lBFY1CUikTv2OHn1TBExN9srMdzAp5MAvq/E44Ri216Sg8yAexbBmIdKHK1m1OLkagnjHANQoRkSBSqUgL/cGKqDkLfZDsxZzCmd8UvUdjJ+FAnOdHJfKZfrzXFQRjx+K1JVrZVjT6tDNnAucxYW57j0Cubx3NlUdWlqMqePaSrnXAlWih4PbkPkW+8tMkNhw9KMlXevzJn+r59Pgu7F5zjtvtZyPiEVmZnO5P708h2/Eg=
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --omit='/home/travis/virtualenv/*' manage.py test tickets.test_models
  pricing
after_success: coveralls
