language: python
python:
- '2.7'
env:
  matrix:
    - DEBUG=0
    - STAGING=1
  global:
    secure: P2ZCZ5T4z7sLjX8DCWEkACI/COlywsMHdtDKWi3T4mULq7zlITPgijvilOUmmhXuvGMpQM4HG9lV1/njyyanUathxRlqeE2kDUNHGpNdsiHZoyPYRYRvnCNgmW5ZRW10LcIb72R1/esM4Pu04YPxUpHkFFYw+tf07WI2OplyDCzamrdDRxAF32KO5jwvA5qldGOSYA8t55P4Z537WtcevhVnUsmj7kxJk+7j5mHctHngBmeioW+1ZOh4w0IIpdcZ7xRGUTo5ERCrNCZyN697NpjmfKKpgiSKf4vFFUD3uaYUpx03Htc0m8z5nGWk6D2PuC9ofIiofZ1Q4op3w4/wjGs3NS37r5vZEO9DRm/bkZH9X+JEPj4SJCnyuLh3mKDgd/3bdhkCODogCoUpiklCDmJtmnbGGnkrazt3Van4Dk+TNW8g7BLcskLJoCC3U6AlSAJNMgK1ouv2sd7TEnijJEGKReeQx0RlL6AB0TLFLzX7GDNFCEXqb3piEJ9lXR0aKEwlk1Zm9fkbZm/S/FkGHeulkbAtbQACV0ORF9Jc39pE5POxip/dySnKlMz4XtDqaexAFlMvxHnZGMh6noixdT/hK9x2Ull/ORcQ8wbqGVqnjFyPUral7O1AVrCsoLzV9jrOlQVbcv02M+zRQeK8PT+MUkiCQge8mXgkZDcLwU0=
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --omit='/home/travis/virtualenv/*' manage.py test tickets.test_models
  pricing
after_success: coveralls
