language: python
python:
  - "2.7"
before_install:
  openssl aes-256-cbc -K $encrypted_eab4b1048f57_key -iv $encrypted_eab4b1048f57_iv -in keys.py.enc -out configuration/keys.py -d
install:
  - pip install -r requirements/common.txt
  - pip install -r requirements/prod.txt 
  - pip install coveralls
script:
  - python manage.py migrate
  - coverage run --omit='/home/travis/virtualenv/*','tickets/test_functional.py' manage.py test
after_success:
  coveralls
